#############################################################
#                   Producer Collections                    #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie only)              #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/movie/producer                            #
#        template_variables:                                #
#          # Sets the style of posters: bw or rainier       #
#          style: bw                                        #
#          # Turn the separator collection on/off           #
#          use_separator: true                              #
#          # Separator style (red, blue, green, gray,       #
#              purple, stb, orig)                           #
#          sep_style: orig                                  #
#          # Sets how the collection is sorted              #
#          sort_by: release.desc                            #
#          # Sets the collection mode of the collections    #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: 19                           #
#          # Radarr Tag for existing items                  #
#          item_radarr_tag:                                 #
#############################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: 19

translations:
  pmm: translations
collections:
  Producers Collections:
    template:
      - name: separator
        separator: producer

dynamic_collections:
  Top Producers:
    type: producer
    data:
      depth: 5
      limit: 25
    template:
      - smart_filter
      - translation
      - shared
    template_variables:
      tmdb_person:
        default: <<value>>
      search_term:
        default: producer
      search_value:
        default: tmdb
      translation_key:
        default: producer
      image:
        default: people/<<style>>/<<key_encoded>>
      style:
        default: bw
      