#############################################################
#               MyAnimeList Chart Collections               #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/anilist                             #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#          # For each collection use the "key" to set       #
#          # the options.                                   #
#          # Available collections                          #
#          #   KEY              COLLECTION                  #
#          #   popular          MyAnimeList Popular         #
#          #   favorited        MyAnimeList Favorited       #
#          #   top              MyAnimeList Top Rated       #
#          #   airing           MyAnimeList Top Airing      #
#          #   season           MyAnimeList Season          #
#                                                           #
#          # Available options. Replace "key" with the      #
#          # desired collection's key from the chart above. #
#                                                           #
#          # Customize summary of collection                #
#          summary_key: A collection of ...                 #
#          # Turn the collection on/off                     #
#          use_key: true                                    #
#          # Determines collection order in it's section    #
#          order_key:                                       #
#          # Determines collection order of the collection  #
#          collection_order_key: custom                     #
#          # Set visible_library for the collection         #
#          visible_library_key:                             #
#          # Set visible_home for the collection            #
#          visible_home_key:                                #
#          # Set visible_shared for the collection          #
#          visible_shared_key:                              #
#          # Set limit for the collection                   #
#          limit_key: 100                                   #
#          # Adds missing from the collection to radarr     #
#          radarr_add_missing_key:                          #
#          # Adds missing from the collection to sonarr     #
#          sonarr_add_missing_key:                          #
#          # Radarr Folder to add to                        #
#          radarr_folder_key:                               #
#          # Sonarr Folder to add to                        #
#          sonarr_folder_key:                               #
#          # Radarr Tag for added missing                   #
#          radarr_tag_key:                                  #
#          # Sonarr Tag for added missing                   #
#          sonarr_tag_key:                                  #
#          # Radarr Tag for existing items                  #
#          item_radarr_tag_key:                             #
#          # Sonarr Tag for existing items                  #
#          item_sonarr_tag_key:                             #
#############################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "01"

translations:
  pmm: translations

templates:
  mal:
    default:
      limit_<<key>>: 100
      chart: <<key>>
    mal_<<chart>>: <<limit_<<key>>>>

  season:
    default:
      limit_season: 100
    mal_season:
      season: current
      sort_by: score
      limit: <<limit_season>>

collections:
  MyAnimeList Popular:
    variables:
      key: popular
    template:
      - name: mal
      - name: shared
      - name: arr
      - name: custom
      - name: translation
        translation_key: mal_popular

  MyAnimeList Favorited:
    variables:
      key: favorited
    template:
      - name: mal
        chart: favorite
      - name: shared
      - name: arr
      - name: custom
      - name: translation
        translation_key: mal_favorited

  MyAnimeList Top Rated:
    variables:
      key: top
    template:
      - name: mal
        chart: all
      - name: shared
      - name: arr
      - name: custom
      - name: translation
        translation_key: mal_top

  MyAnimeList Top Airing:
    variables:
      key: airing
    template:
      - name: mal
      - name: shared
      - name: arr
      - name: custom
      - name: translation
        translation_key: mal_airing

  MyAnimeList Season:
    variables:
      key: season
    template:
      - name: season
      - name: shared
      - name: arr
      - name: custom
      - name: translation
        translation_key: mal_season
