#############################################################
#                  TMDb Chart Collections                   #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/tmdb                                #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#          # For each collection use the "key" to set       #
#          # the options.                                   #
#          # Available collections                          #
#          #   KEY              COLLECTION                  #
#          #   airing           TMDb Airing Today           #
#          #   air              TMDb On The Air             #
#          #   popular          TMDb Popular                #
#          #   top              TMDb Top Rated              #
#          #   trending         TMDb Trending               #
#                                                           #
#          # Available options. Replace "key" with the      #
#          # desired collection's key from the chart above. #
#                                                           #
#          # Customize summary of collection                #
#          summary_key: A collection of ...                 #
#          # Turn the collection on/off                     #
#          use_key: true                                    #
#          # Determines collection order in its section     #
#          order_key:                                       #
#          # Determines collection order of the collection  #
#          collection_order_key: custom                     #
#          # Set visible_library for the collection         #
#          visible_library_key:                             #
#          # Set visible_home for the collection            #
#          visible_home_key:                                #
#          # Set visible_shared for the collection          #
#          visible_shared_key:                              #
#          # Set limit for the collection                   #
#          limit_key: 100                                   #
#          # Adds missing from the collection to radarr     #
#          radarr_add_missing_key:                          #
#          # Adds missing from the collection to sonarr     #
#          sonarr_add_missing_key:                          #
#          # Radarr Folder to add to                        #
#          radarr_folder_key:                               #
#          # Sonarr Folder to add to                        #
#          sonarr_folder_key:                               #
#          # Radarr Tag for added missing                   #
#          radarr_tag_key:                                  #
#          # Sonarr Tag for added missing                   #
#          sonarr_tag_key:                                  #
#          # Radarr Tag for existing items                  #
#          item_radarr_tag_key:                             #
#          # Sonarr Tag for existing items                  #
#          item_sonarr_tag_key:                             #
#############################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "01"

translations:
  pmm: translations

templates:

  tmdb:
    default:
      limit_<<key>>: 100
      chart: <<key>>
    tmdb_<<chart>>: <<limit_<<key>>>>

collections:

  TMDb Airing Today:
    variables:
      key: airing
    template:
      - name: tmdb
        chart: airing_today
      - name: shared
        allowed_libraries: show
      - name: arr
      - name: custom
      - name: translation
        translation_key: tmdb_airing

  TMDb On The Air:
    variables:
      key: air
    template:
      - name: tmdb
        chart: on_the_air
      - name: shared
        allowed_libraries: show
      - name: arr
      - name: custom
      - name: translation
        translation_key: tmdb_air

  TMDb Popular:
    variables:
      key: popular
    template:
      - name: tmdb
      - name: shared
      - name: arr
      - name: custom
      - name: translation
        translation_key: tmdb_popular

  TMDb Top Rated:
    variables:
      key: top
    template:
      - name: tmdb
        chart: top_rated
      - name: shared
      - name: arr
      - name: custom
      - name: translation
        translation_key: tmdb_top

  TMDb Trending:
    variables:
      key: trending
    template:
      - name: tmdb
        chart: trending_weekly
      - name: shared
      - name: arr
      - name: custom
      - name: translation
        translation_key: tmdb_trending