name: Release

on:
  release:
    types: [ published ]

jobs:

  release:

    runs-on: ubuntu-latest
    steps:

      - name: Send Discord Release Notification
        uses: nhevia/discord-styled-releases@main
        with:
          webhook_id: ${{ secrets.RELEASE_WEBHOOK_ID }}
          webhook_token: ${{ secrets.RELEASE_WEBHOOK_TOKEN }}